services:
  sofi-mail:
    image: ${SOFI_IMAGE:-sofi-mail:local}

    volumes:
      - type: bind
        source: ./.env
        target: /opt/sofi-mail/.env
        read_only: true
        bind:
          create_host_path: false
      - "${SOFI_DATA_DIR:-/srv/sofi-mail/data}:/opt/sofi-mail/data"
      - "${SOFI_CERTS_DIR:-/srv/sofi-mail/certs}:/opt/sofi-mail/certs:ro"

    restart: unless-stopped
    stop_grace_period: 330s
    read_only: true
    tmpfs:
      - /tmp:mode=1777,size=64m
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
